#!/bin/bash

# Figure out where it is installed
FWDIR="$(cd `dirname $0`; pwd)"

# Export this as VARYS_HOME
export VARYS_HOME="$FWDIR"

# Load environment variables from conf/varys-env.sh, if it exists
if [ -e $FWDIR/conf/varys-env.sh ] ; then
  . $FWDIR/conf/varys-env.sh
fi

# Find out which java to use
if [ `command -v java` ]; then
  RUNNER="java"
else
  if [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME is not set" >&2
    exit 1
  fi
  RUNNER="${JAVA_HOME}/bin/java"
fi

# Set JAVA_OPTS to be able to load native libraries and to set heap size
JAVA_OPTS="$VARYS_JAVA_OPTS"
JAVA_OPTS+=" -Djava.library.path=$VARYS_LIBRARY_PATH"
# Load extra JAVA_OPTS from conf/java-opts, if it exists
if [ -e $FWDIR/conf/java-opts ] ; then
  JAVA_OPTS+=" `cat $FWDIR/conf/java-opts`"
fi
export JAVA_OPTS

# Build up classpath
CLASSPATH="$FWDIR/varys.jar"
for jar in `find $FWDIR/lib -name '*jar'`; do
  CLASSPATH+=":$jar"
done
CLASSPATH+=":$VARYS_CLASSPATH"

exec "$RUNNER" -cp "$CLASSPATH" "$@"
