#!/bin/bash

VARYS_PATH=`pwd`

SLAVES=$VARYS_PATH/conf/slaves

# Start master
$VARYS_PATH/start-master

# Start slaves
for peer in `cat $SLAVES`; do
  echo $peer
  ssh $peer "cd $VARYS_PATH;./start-slave" &
done
