#!/bin/sh

VARYS_PATH=`pwd`

MASTER=$VARYS_PATH/conf/masters
SLAVES=$VARYS_PATH/conf/slaves

# Stop all
for peer in `cat $MASTER $SLAVES`; do
  echo $peer
  ssh $peer "cd $VARYS_PATH;./stop-local"
done
