#!/bin/sh

VARYS_PATH=`pwd`

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

MASTER=$VARYS_PATH/masters
SLAVES=$VARYS_PATH/slaves

# Stop all
for peer in `cat $MASTER $SLAVES`; do
  echo $peer
  screen -dmS "stop-peer-$peer" ssh -t $SSH_OPTS $peer "cd $VARYS_PATH;./stop-local"
done

# For some reason, some dead screens hang around. Wipe them away.
sleep 1
screen -wipe > /dev/null 2> /dev/null
