/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package varys;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MachineStat implements org.apache.thrift.TBase<MachineStat, MachineStat._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MachineStat");

  private static final org.apache.thrift.protocol.TField RX_BPS_FIELD_DESC = new org.apache.thrift.protocol.TField("rx_bps", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField TX_BPS_FIELD_DESC = new org.apache.thrift.protocol.TField("tx_bps", org.apache.thrift.protocol.TType.DOUBLE, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MachineStatStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MachineStatTupleSchemeFactory());
  }

  public double rx_bps; // required
  public double tx_bps; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RX_BPS((short)1, "rx_bps"),
    TX_BPS((short)2, "tx_bps");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RX_BPS
          return RX_BPS;
        case 2: // TX_BPS
          return TX_BPS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RX_BPS_ISSET_ID = 0;
  private static final int __TX_BPS_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RX_BPS, new org.apache.thrift.meta_data.FieldMetaData("rx_bps", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.TX_BPS, new org.apache.thrift.meta_data.FieldMetaData("tx_bps", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MachineStat.class, metaDataMap);
  }

  public MachineStat() {
  }

  public MachineStat(
    double rx_bps,
    double tx_bps)
  {
    this();
    this.rx_bps = rx_bps;
    setRx_bpsIsSet(true);
    this.tx_bps = tx_bps;
    setTx_bpsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MachineStat(MachineStat other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.rx_bps = other.rx_bps;
    this.tx_bps = other.tx_bps;
  }

  public MachineStat deepCopy() {
    return new MachineStat(this);
  }

  @Override
  public void clear() {
    setRx_bpsIsSet(false);
    this.rx_bps = 0.0;
    setTx_bpsIsSet(false);
    this.tx_bps = 0.0;
  }

  public double getRx_bps() {
    return this.rx_bps;
  }

  public MachineStat setRx_bps(double rx_bps) {
    this.rx_bps = rx_bps;
    setRx_bpsIsSet(true);
    return this;
  }

  public void unsetRx_bps() {
    __isset_bit_vector.clear(__RX_BPS_ISSET_ID);
  }

  /** Returns true if field rx_bps is set (has been assigned a value) and false otherwise */
  public boolean isSetRx_bps() {
    return __isset_bit_vector.get(__RX_BPS_ISSET_ID);
  }

  public void setRx_bpsIsSet(boolean value) {
    __isset_bit_vector.set(__RX_BPS_ISSET_ID, value);
  }

  public double getTx_bps() {
    return this.tx_bps;
  }

  public MachineStat setTx_bps(double tx_bps) {
    this.tx_bps = tx_bps;
    setTx_bpsIsSet(true);
    return this;
  }

  public void unsetTx_bps() {
    __isset_bit_vector.clear(__TX_BPS_ISSET_ID);
  }

  /** Returns true if field tx_bps is set (has been assigned a value) and false otherwise */
  public boolean isSetTx_bps() {
    return __isset_bit_vector.get(__TX_BPS_ISSET_ID);
  }

  public void setTx_bpsIsSet(boolean value) {
    __isset_bit_vector.set(__TX_BPS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RX_BPS:
      if (value == null) {
        unsetRx_bps();
      } else {
        setRx_bps((Double)value);
      }
      break;

    case TX_BPS:
      if (value == null) {
        unsetTx_bps();
      } else {
        setTx_bps((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RX_BPS:
      return Double.valueOf(getRx_bps());

    case TX_BPS:
      return Double.valueOf(getTx_bps());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RX_BPS:
      return isSetRx_bps();
    case TX_BPS:
      return isSetTx_bps();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MachineStat)
      return this.equals((MachineStat)that);
    return false;
  }

  public boolean equals(MachineStat that) {
    if (that == null)
      return false;

    boolean this_present_rx_bps = true;
    boolean that_present_rx_bps = true;
    if (this_present_rx_bps || that_present_rx_bps) {
      if (!(this_present_rx_bps && that_present_rx_bps))
        return false;
      if (this.rx_bps != that.rx_bps)
        return false;
    }

    boolean this_present_tx_bps = true;
    boolean that_present_tx_bps = true;
    if (this_present_tx_bps || that_present_tx_bps) {
      if (!(this_present_tx_bps && that_present_tx_bps))
        return false;
      if (this.tx_bps != that.tx_bps)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(MachineStat other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    MachineStat typedOther = (MachineStat)other;

    lastComparison = Boolean.valueOf(isSetRx_bps()).compareTo(typedOther.isSetRx_bps());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRx_bps()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rx_bps, typedOther.rx_bps);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTx_bps()).compareTo(typedOther.isSetTx_bps());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTx_bps()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tx_bps, typedOther.tx_bps);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MachineStat(");
    boolean first = true;

    sb.append("rx_bps:");
    sb.append(this.rx_bps);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tx_bps:");
    sb.append(this.tx_bps);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MachineStatStandardSchemeFactory implements SchemeFactory {
    public MachineStatStandardScheme getScheme() {
      return new MachineStatStandardScheme();
    }
  }

  private static class MachineStatStandardScheme extends StandardScheme<MachineStat> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MachineStat struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RX_BPS
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.rx_bps = iprot.readDouble();
              struct.setRx_bpsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TX_BPS
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.tx_bps = iprot.readDouble();
              struct.setTx_bpsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MachineStat struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RX_BPS_FIELD_DESC);
      oprot.writeDouble(struct.rx_bps);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TX_BPS_FIELD_DESC);
      oprot.writeDouble(struct.tx_bps);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MachineStatTupleSchemeFactory implements SchemeFactory {
    public MachineStatTupleScheme getScheme() {
      return new MachineStatTupleScheme();
    }
  }

  private static class MachineStatTupleScheme extends TupleScheme<MachineStat> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MachineStat struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRx_bps()) {
        optionals.set(0);
      }
      if (struct.isSetTx_bps()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetRx_bps()) {
        oprot.writeDouble(struct.rx_bps);
      }
      if (struct.isSetTx_bps()) {
        oprot.writeDouble(struct.tx_bps);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MachineStat struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.rx_bps = iprot.readDouble();
        struct.setRx_bpsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.tx_bps = iprot.readDouble();
        struct.setTx_bpsIsSet(true);
      }
    }
  }

}

